### ISSUE TITLE
Manage list command when db is empty

### ISSUE THREAD

**Issue by julbrs** [gbandsmith/bitbucket-chat-bot#1]
Currently on branch **add-list-functionality**

There is this message when I run `list`: 
![image](https://user-images.githubusercontent.com/4988590/50175964-2642b280-02cc-11e9-94bb-d79014b4cc51.png)

Can it be shown as:

**No connected repositories**

THANKS !

**Comment by amitrica** [comment]
Seem to work:
![image](https://user-images.githubusercontent.com/12054805/50177513-2e045600-02d0-11e9-9e73-a58cee3d5c2c.png)

**Comment by julbrs** [comment]
Fixed since _db5317a5d3635dd0fbdf1fc6931ff8177127ab0c_ thanks @amitrica !
